package com.lionde.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.NAME
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.TOKEN
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.GMT_CREATE
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.GMT_MODIFIED
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.BIO
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLEUSER.AVATAR_URL
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.ID
     *
     * @return the value of TABLEUSER.ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.ID
     *
     * @param id the value for TABLEUSER.ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.ACCOUNT_ID
     *
     * @return the value of TABLEUSER.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.ACCOUNT_ID
     *
     * @param accountId the value for TABLEUSER.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.NAME
     *
     * @return the value of TABLEUSER.NAME
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.NAME
     *
     * @param name the value for TABLEUSER.NAME
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.TOKEN
     *
     * @return the value of TABLEUSER.TOKEN
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.TOKEN
     *
     * @param token the value for TABLEUSER.TOKEN
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.GMT_CREATE
     *
     * @return the value of TABLEUSER.GMT_CREATE
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.GMT_CREATE
     *
     * @param gmtCreate the value for TABLEUSER.GMT_CREATE
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.GMT_MODIFIED
     *
     * @return the value of TABLEUSER.GMT_MODIFIED
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.GMT_MODIFIED
     *
     * @param gmtModified the value for TABLEUSER.GMT_MODIFIED
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.BIO
     *
     * @return the value of TABLEUSER.BIO
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.BIO
     *
     * @param bio the value for TABLEUSER.BIO
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLEUSER.AVATAR_URL
     *
     * @return the value of TABLEUSER.AVATAR_URL
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLEUSER.AVATAR_URL
     *
     * @param avatarUrl the value for TABLEUSER.AVATAR_URL
     *
     * @mbg.generated Sun Aug 07 19:28:04 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}