CREATE TABLE TABLEUSER
(
    ID BIGINT AUTO_INCREMENT,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    TOKEN VARCHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    BIO VARCHAR(256) NULL,
    AVATAR_URL VARCHAR(100) NULL,
    CONSTRAINT TABLEUSER_PK
        PRIMARY KEY (ID)
);

