CREATE TABLE QUESTION
(
    ID BIGINT AUTO_INCREMENT,
    TITLE VARCHAR(50),
    DESCRIPTION TEXT,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    CREATOR BIGINT NOT NULL,
    COMMENT_COUNT INT default 0,
    VIEW_COUNT INT default 0,
    LIKE_COUNT INT default 0,
    TAG VARCHAR(256),
    CONSTRAINT QUESTION_PK
        PRIMARY KEY (ID)
);

